# Site settings
title: HTML Workshop
email: juuso.stromberg@gmail.com
description: > # HTML Workshop for Aalto University's Economics Students
baseurl: "/html-workshop" # the subpath of your site, e.g. /blog/
url: "http://juzmach.github.io" # the base hostname & protocol for your site
twitter_username: jstrmbrg
github_username:  Juzmach

markdown: kramdown 
encoding: UTF-8
highlighter: pygments
safe: true

kramdown:
  input: GFM
